/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Text, View } from "@aws-amplify/ui-react";
export default function Studentlist(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1835px"
      height="102px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Studentlist")}
      {...rest}
    >
      <View
        width="76px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="0%"
        right="95.86%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 231")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="41px"
        height="25px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-18.63%"
        left="0.98%"
        right="96.78%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="選択"
        {...getOverrideProps(overrides, "\u9078\u629E")}
      ></Text>
      <View
        width="195px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="4.14%"
        right="85.23%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 11")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="70px"
        height="26px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="95.1%"
        bottom="-20.59%"
        left="8.77%"
        right="87.41%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="氏名"
        {...getOverrideProps(overrides, "\u6C0F\u540D")}
      ></Text>
      <View
        width="222px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="14.77%"
        right="73.13%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 13")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="111px"
        height="25px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-18.63%"
        left="18.64%"
        right="75.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="フリガナ"
        {...getOverrideProps(overrides, "\u30D5\u30EA\u30AC\u30CA")}
      ></Text>
      <View
        width="163px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="26.87%"
        right="64.25%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 259")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="88px"
        height="28px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-21.57%"
        left="29.75%"
        right="65.45%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="大学名"
        {...getOverrideProps(overrides, "\u5927\u5B66\u540D")}
      ></Text>
      <View
        width="195px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="35.75%"
        right="53.62%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 269")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="108px"
        height="28px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-21.57%"
        left="38.58%"
        right="55.53%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="説明会日時"
        {...getOverrideProps(overrides, "\u8AAC\u660E\u4F1A\u65E5\u6642")}
      ></Text>
      <View
        width="195px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="46.38%"
        right="43%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 279")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="157px"
        height="51px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-44.12%"
        left="48.61%"
        right="42.83%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="一次面接日時"
        {...getOverrideProps(overrides, "\u4E00\u6B21\u9762\u63A5\u65E5\u6642")}
      ></Text>
      <View
        width="195px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="57%"
        right="32.37%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 289")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="153px"
        height="53px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-46.08%"
        left="60%"
        right="31.66%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="座談会日時"
        {...getOverrideProps(overrides, "\u5EA7\u8AC7\u4F1A\u65E5\u6642")}
      ></Text>
      <View
        width="195px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="67.63%"
        right="21.74%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 304")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="156px"
        height="53px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-46.08%"
        left="69.86%"
        right="21.63%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="最終面接日時"
        {...getOverrideProps(overrides, "\u5F79\u54E1\u9762\u63A5\u65E5\u6642")}
      ></Text>
      <View
        width="235px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="78.2%"
        right="8.99%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 14")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="211px"
        height="27px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="94.12%"
        bottom="-20.59%"
        left="79.46%"
        right="9.05%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="当社を知ったきっかけ"
        {...getOverrideProps(
          overrides,
          "\u5F53\u793E\u3092\u77E5\u3063\u305F\u304D\u3063\u304B\u3051"
        )}
      ></Text>
      <View
        width="163px"
        height="85px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100%"
        bottom="-83.33%"
        left="91.01%"
        right="0.11%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 299")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="82px"
        height="28px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="93.14%"
        bottom="-20.59%"
        left="93.35%"
        right="2.18%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="学生状況"
        {...getOverrideProps(overrides, "\u5B66\u751F\u72B6\u6CC1")}
      ></Text>
      <View
        width="1835px"
        height="102px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(198,235,255,1)"
        {...getOverrideProps(overrides, "Rectangle 10")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="155px"
        height="30px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="11.76%"
        bottom="58.82%"
        left="48.34%"
        right="43.22%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="学生一覧"
        {...getOverrideProps(overrides, "\u5B66\u751F\u4E00\u89A7")}
      ></Text>
    </View>
  );
}
